### ISSUE TITLE
Customize minetest.conf in minetest-chart

### ISSUE THREAD

**Issue by metacoma** [9mine/9mine#96]
add the possibility of customization minetest.conf in values.yml
https://github.com/9mine/charts/blob/main/charts/minetest/values.yaml

smth like that:

```
image:
  repository: 9mine/minetest
  pullPolicy: Always
  tag: "master"
  
configuration:
  server_name: "servername"
  server_description: "description"
  server_addres: "demo.metacoma.io"
  ....
  default_privs: "interact, shout, give, teleport, bring, fast, fly, noclip, settime, privs, basic_privs, ban, rollback, server"
```
